version: "2"

linters:
  # errcheck, govet, ineffassign, staticcheck, unused
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - unconvert
    - unparam
    - usestdlibvars

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/KKolyasik/max-benefits
